{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python368jvsc74a57bd0f7291e4b392a32fbfa525b87d1bbd0a3d888adf3d0deca0c205c61b9e7284b82",
   "display_name": "Python 3.6.8 64-bit"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "x=np.arange(7,142,3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "of=open('test.txt','a')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "j=5\n",
    "k=3\n",
    "for i in x:\n",
    "\n",
    "    of.write(\"\"\"Dim hybridShapePlaneOffset%d As HybridShapePlaneOffset\n",
    "Set hybridShapePlaneOffset%d = hybridShapes1.Item(\"平面.%d\")\n",
    "\n",
    "Dim reference%d As Reference\n",
    "Set reference%d = part1.CreateReferenceFromObject(hybridShapePlaneOffset%d)\n",
    "\n",
    "Dim hybridShapePlaneOffset%d As HybridShapePlaneOffset\n",
    "Set hybridShapePlaneOffset%d = hybridShapeFactory1.AddNewPlaneOffset(reference%d, -0.01, False)\n",
    "\n",
    "hybridBody1.AppendHybridShape hybridShapePlaneOffset%d\n",
    "\n",
    "part1.InWorkObject = hybridShapePlaneOffset%d\n",
    "\n",
    "part1.Update\n",
    "\n",
    "Dim hybridShapeSplit%d As HybridShapeSplit\n",
    "Set hybridShapeSplit%d = hybridShapes1.Item(\"分割.%d\")\n",
    "\n",
    "Dim reference%d As Reference\n",
    "Set reference%d = part1.CreateReferenceFromObject(hybridShapeSplit%d)\n",
    "\n",
    "Dim reference%d As Reference\n",
    "Set reference%d = part1.CreateReferenceFromObject(hybridShapePlaneOffset%d)\n",
    "\n",
    "Dim hybridShapeSplit%d As HybridShapeSplit\n",
    "Set hybridShapeSplit%d = hybridShapeFactory1.AddNewHybridSplit(reference%d, reference%d, 1)\n",
    "\n",
    "hybridShapeFactory1.GSMVisibility reference%d, 0\n",
    "\n",
    "hybridShapeSplit%d.ExtrapolationType = 1\n",
    "\n",
    "hybridBody1.AppendHybridShape hybridShapeSplit%d\n",
    "\n",
    "part1.InWorkObject = hybridShapeSplit%d\n",
    "\n",
    "part1.Update\n",
    "\n",
    "part1.Update\n",
    "\n",
    "Dim drawingDocument%d As DrawingDocument\n",
    "Set drawingDocument%d = documents1.Add(\"Drawing\")\n",
    "\n",
    "drawingDocument%d.Standard = catISO\n",
    "\n",
    "Dim drawingSheets%d As DrawingSheets\n",
    "Set drawingSheets%d = drawingDocument%d.Sheets\n",
    "\n",
    "Dim drawingSheet%d As DrawingSheet\n",
    "Set drawingSheet%d = drawingSheets%d.Item(\"页.1\")\n",
    "\n",
    "drawingSheet%d.PaperSize = catPaperA0\n",
    "\n",
    "drawingSheet%d.[Scale] = 1#\n",
    "\n",
    "drawingSheet%d.Orientation = catPaperLandscape\n",
    "\n",
    "Dim drawingViews%d As DrawingViews\n",
    "Set drawingViews%d = drawingSheet%d.Views\n",
    "\n",
    "Dim drawingView%d As DrawingView\n",
    "Set drawingView%d = drawingViews%d.Add(\"AutomaticNaming\")\n",
    "\n",
    "Dim drawingViewGenerativeLinks%d As DrawingViewGenerativeLinks\n",
    "Set drawingViewGenerativeLinks%d = drawingView%d.GenerativeLinks\n",
    "\n",
    "Dim drawingViewGenerativeBehavior%d As DrawingViewGenerativeBehavior\n",
    "Set drawingViewGenerativeBehavior%d = drawingView%d.GenerativeBehavior\n",
    "\n",
    "drawingViewGenerativeBehavior%d.Document = product1\n",
    "\n",
    "drawingViewGenerativeBehavior%d.DefineFrontView 0#, 1#, 0#, 0#, 0#, 1#\n",
    "\n",
    "drawingView%d.X = 594.5\n",
    "\n",
    "drawingView%d.Y = 420.5\n",
    "\n",
    "drawingView%d.[Scale] = 1#\n",
    "\n",
    "Set drawingViewGenerativeBehavior%d = drawingView%d.GenerativeBehavior\n",
    "\n",
    "drawingViewGenerativeBehavior%d.Update\n",
    "\n",
    "drawingView%d.Activate\n",
    "\n",
    "Set drawingDocument%d = CATIA.ActiveDocument\n",
    "\n",
    "drawingDocument%d.SaveAs \"E:\\\\Users\\\\acer\\\\Desktop\\\\fuselageout\\\\fuselage302\\cat\\\\tt%d.CATDrawing\"\n",
    "\n",
    "Dim specsAndGeomWindow%d As SpecsAndGeomWindow\n",
    "Set specsAndGeomWindow%d = CATIA.ActiveWindow\n",
    "\n",
    "specsAndGeomWindow%d.Close\n",
    "\n",
    "Set drawingDocument%d = CATIA.ActiveDocument\n",
    "\n",
    "drawingDocument%d.Close\n",
    "\n",
    "Dim selection%d As Selection\n",
    "Set selection%d = partDocument1.Selection\n",
    "\n",
    "Dim visPropertySet%d As VisPropertySet\n",
    "Set visPropertySet%d = selection%d.VisProperties\n",
    "\n",
    "Set hybridShapes1 = hybridShapeSplit%d.Parent\n",
    "\n",
    "Dim bSTR%d As String\n",
    "bSTR%d = hybridShapeSplit%d.Name\n",
    "\n",
    "selection%d.Add hybridShapeSplit%d\n",
    "\n",
    "Set visPropertySet%d = visPropertySet%d.Parent\n",
    "\n",
    "Dim bSTR%d As String\n",
    "bSTR%d = visPropertySet%d.Name\n",
    "\n",
    "Dim bSTR%d As String\n",
    "bSTR%d = visPropertySet%d.Name\n",
    "\n",
    "visPropertySet%d.SetShow 1\n",
    "\n",
    "selection%d.Clear\n",
    "\n",
    "\"\"\"%(j,j,k,i,i,j,j+1,j+1,i,j+1,j+1,j,j,k,i+1,i+1,j,i+2,i+2,j+1,j+1,j+1,i+1,i+2,i+1,j+1,j+1,j+1,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,j+1,i,i,j+1,k,j+1,k,k,i+1,i+1,k,i+2,i+2,k,k,k))\n",
    "    j+=2\n",
    "    k+=1\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "of.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ]
}